### ISSUE TITLE
Network.Wai.Logger no longer exports DateCacheGetter

### ISSUE THREAD

**Issue by erikd** [kazu-yamamoto/logger#90]
I'm currently working on getting Yesod working for ghc-8.0 which is pretty close to being formally released.

Building the git version of `yesod-core` against the git version of `wai-logger` I get:

```
Yesod/Core/Types.hs:52:54: error:
    Module ‘Network.Wai.Logger’ does not export ‘DateCacheGetter’
```

Should that be fixed in `yesod-core` or `wai-logger`?

**Comment by felixonmars** [comment]
I just opened a PR to fix it on yesod-core: https://github.com/yesodweb/yesod/pull/1215

**Comment by snoyberg** [comment]
This does look like a regression in wai-logger. @kazu-yamamoto any objection to releasing a new version of wai-logger that re-adds that type synonym?

Pinging @winterland1989

**Comment by kazu-yamamoto** [comment]
I have no objections. I believed that wai-logger 2.2.6 is backward-compatible but it is not. So, we need to fix it.

**Comment by winterland1989** [comment]
OK, i'll do it.

**Comment by kazu-yamamoto** [comment]
@winterland1989 I'm working. :-)

**Comment by winterland1989** [comment]
Please proceed, i have another issue here, the clean up action [here](https://github.com/kazu-yamamoto/logger/blob/master/fast-logger/System/Log/FastLogger.hs#L205) and [here](https://github.com/kazu-yamamoto/logger/blob/master/fast-logger/System/Log/FastLogger.hs#L235) really should not be a no-op, it should be `rmLoggerSet lgrset` too, because `rmLoggerSet` will ensure flush in face of exceptions. can you fix that too?

**Comment by kazu-yamamoto** [comment]
@winterland1989 @snoyberg Please check the patch above.

**Comment by kazu-yamamoto** [comment]
> Please proceed, i have another issue here, the clean up action here and here really should not be a no-op, it should be rmLoggerSet lgrset too, because rmLoggerSet will ensure flush in face of exceptions. can you fix that too?

@winterland1989 Can you write a test case to demonstrate the issue?

**Comment by snoyberg** [comment]
LGTM

**Comment by winterland1989** [comment]
It should solve the back-compatible issue. i haven't got an idea to add test to fast-logger, but i'll try.

**Comment by kazu-yamamoto** [comment]
I have released wai-logger v2.2.7.

**Comment by kazu-yamamoto** [comment]
@snoyberg BTW, do you know any tools to confirm backward compatibility of packages? I should use such tools before releasing.

**Comment by erikd** [comment]
@kazu-yamamoto I don't know of any tools, but you can use http://packdeps.haskellers.com/reverse to find the reverse dependencies of your package, set up a cabal sandbox, `cabal sandbox add-source <your package>` and then `cabal install` all the reverse dependencies into the sandbox.

Any breakage due to changes in your package will reveal themselves.

**Comment by kazu-yamamoto** [comment]
Yeah, that's one way. But I want to have tools to just compare exports of two versions of a package.

**Comment by snoyberg** [comment]
Sorry, I'm unaware of any tooling.

**Comment by winterland1989** [comment]
I think we really should bump the minor version if we want to be sure no large breakage happening.

**Comment by erikd** [comment]
Afaiac its fixed with the release of 2.2.7.

**Comment by kazu-yamamoto** [comment]
@winterland1989 What we should do is try to maintain backward compatibility as much as possible and bump minor versions. We bump the major versions if we breaks backward compatibility. In this case, we need strong/reasonable reasons to break backward compatibility.
