### PR TITLE
Fix #106 by correcting the default signature for MonadLoggerIO

### LINKED ISSUE #106: ‘m’ is a rigid type variable bound: build failure with 8.0.1.20161022
Build log is here: https://gist.github.com/ilovezfs/c62fa40eb3f61569cb0e03f8cd3320a8

Several errors that look like

```
Control/Monad/Logger.hs:249:10: error:
    • Couldn't match type ‘m’ with ‘IdentityT m’
      ‘m’ is a rigid type variable bound by
        the instance declaration at Control/Monad/Logger.hs:249:10
      Expected type: IdentityT
                       m (Loc -> LogSource -> LogLevel -> LogStr -> IO ())
        Actual type: IdentityT
                       (IdentityT m) (Loc -> LogSource -> LogLevel -> LogStr -> IO ())
```

Commenting out https://github.com/kazu-yamamoto/logger/blob/master/monad-logger/Control/Monad/Logger.hs#L249-L264 seems to work around the problem.

### PR DESCRIPTION
**Pull request by RyanGlScott**
As pointed out in [GHC Trac #12784](https://ghc.haskell.org/trac/ghc/ticket/12784), `monad-logger` is failing to compile on GHC 8.0.2 because it's using a bogus default type signature for `askLoggerIO` in the `MonadLoggerIO` class. Luckily, it's a simple fix.

Fixes #106.

### CODE REVIEW

**Comment by snoyberg** [comment]
Thanks!

**Comment by ilovezfs** [comment]
Thanks @RyanGlScott and @snoyberg!
