### ISSUE TITLE
monad-logger-0.3.28 doesn't build on GHC 7.8.4

### ISSUE THREAD

**Issue by YoEight** [kazu-yamamoto/logger#153]
Greetings,

```
Downloading monad-logger-0.3.28...
Configuring monad-logger-0.3.28...
Building monad-logger-0.3.28...
Failed to install monad-logger-0.3.28
Build log ( /root/.cabal/logs/monad-logger-0.3.28.log ):
Configuring monad-logger-0.3.28...
Building monad-logger-0.3.28...
Preprocessing library monad-logger-0.3.28...
[1 of 1] Compiling Control.Monad.Logger ( Control/Monad/Logger.hs, dist/build/Control/Monad/Logger.o )

Control/Monad/Logger.hs:459:58:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<*>’ (imported from Control.Applicative)

Control/Monad/Logger.hs:464:29:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<*>’ (imported from Control.Applicative)

Control/Monad/Logger.hs:476:75:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<*>’ (imported from Control.Applicative)

Control/Monad/Logger.hs:487:45:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<*>’ (imported from Control.Applicative)

Control/Monad/Logger.hs:490:48:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<*>’ (imported from Control.Applicative)
```
If you don't have the time, I might be able to submit a patch later this week.

Thanks for your work.

**Comment by snoyberg** [comment]
Thanks for the report. I didn't realize until this report that 7.8.4 isn't tested by Travis. I see a few options at this point:

1. Accept that 7.8.4 isn't being tested properly and add a lower bound on base in this package
2. Make a one time patch and release, and accept that it'll probably break again in the future
3. Separate monad-logger into its own package that includes 7.8.4 testing

Are you currently using new versions of monad-logger on 7.8.4, or is this an automated test that discovered the incompatibility?

**Comment by YoEight** [comment]
Thanks for the quick response. I don't personally use 7.8.4 anymore. I'm just a maintainer that tries to support as many GHC versions as I can (I started that lib back when 7.8 was around). I think `2` is a reasonable solution. I guess when 8.4 will be released, there would be no reason to support a compiler that old.

It's an automated test that discovered the incompatibility (my CircleCI jobs). I didn't notice the breakage because my Travis CI breaks for six months because of out of memory errors. Those issues lead me to move to CircleCI lately.

**Comment by snoyberg** [comment]
I just looked into patching this. If you'd like to send a PR, I'll be happy to review and merge. But this is looking pretty hairy for not enough return. I'm more tempted to tighten the lower bound instead.

**Comment by snoyberg** [comment]
Fixed by #153, thanks!

**Comment by YoEight** [comment]
Thanks for cutting a new version that fast!

**Comment by snoyberg** [comment]
No problem, thanks for the PR
